name: Test download

on:
  push:
    branches: [ dev ]

jobs:
  test:

    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        ruby: [ '3.0', '3.1', '3.2' ]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }} # Not needed with a .ruby-version file
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Update gem
      run: |
        sudo gem update --system
    - name: Install nsrr and download a samll part of SHHS to do test
      # NOT finished yet
      # have to know how to login using GitHub secrets
      # and download a small part of SHHS using
      # `nsrr download shhs/polysomnography/edfs/shhs1/shhs1-20000*.edf`
      run: |
        sudo gem install nsrr --no-document
        nsrr download shhs/polysomnography/edfs/shhs1/ --file="shhs1-20000*.edf" --token=${{ secrets.NSRR_TOKEN }}
