name: Test download

on:
  push:
    branches: [ dev ]

jobs:
  test:

    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        ruby: [ '3.0', '3.1', '3.2' ]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }} # Not needed with a .ruby-version file
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Install nsrr and download a samll part of SHHS to do test
      run: |
        gem install nsrr --no-document
        nsrr download shhs/polysomnography/edfs/shhs1/ --file="^shhs1\-20010.*\.edf" --token=${{ secrets.NSRR_TOKEN }}
        nsrr download shhs/polysomnography/annotations-events-nsrr/shhs1/ --file="^shhs1\-20010.*\-nsrr\.xml" --token=${{ secrets.NSRR_TOKEN }}
        nsrr download shhs/polysomnography/annotations-events-profusion/shhs1/ --file="^shhs1\-20010.*\-profusion\.xml" --token=${{ secrets.NSRR_TOKEN }}
        nsrr download shhs/polysomnography/annotations-events-rpoints/shhs1/ --file="^shhs1\-20010.*\-rpoint\.csv" --token=${{ secrets.NSRR_TOKEN }}
        nsrr download shhs/datasets/ --shallow --token=${{ secrets.NSRR_TOKEN }}
        nsrr download shhs/datasets/hrv-analysis/ --token=${{ secrets.NSRR_TOKEN }}
        mkdir -p ~/tmp/nsrr-data/
        mv shhs/ ~/tmp/nsrr-data/
        du -sh ~/tmp/nsrr-data/*
        rm -rf ~/tmp/nsrr-data/
